
GO
CREATE DATABASE QLVATLIEU_FACT

USE QLVATLIEU_FACT

CREATE TABLE DIM_THOIGIAN
(
	MATHOIGIAN NCHAR(20) NOT NULL,
	NGAY INT,
	THANG INT,
	NAM INT,
	CONSTRAINT PK_THOIGIAN PRIMARY KEY(MATHOIGIAN)
)

CREATE TABLE DIM_KHUVUC
(
	MAKV NCHAR(20) NOT NULL,
	TENKV NVARCHAR(100),
	CONSTRAINT PK_KHUVUC PRIMARY KEY(MAKV)
)

CREATE TABLE DIM_CHINHANH
(
	MACHINHANH NCHAR(20) NOT NULL,	
	TENCHINHANH NVARCHAR(200),	
	DIACHI NVARCHAR(100),
	CONSTRAINT PK_CHINHANH PRIMARY KEY(MACHINHANH)	
)

CREATE TABLE DIM_NHACUNGCAP
(
	MANCC NCHAR(20) NOT NULL,
	TENNCC NVARCHAR(100),
	DIACHI NVARCHAR(100),
	DIENTHOAI INT,
	CONSTRAINT PK_NCC PRIMARY KEY(MANCC)
)

CREATE TABLE DIM_LOAISANPHAM
(
	MALOAI NCHAR(20) NOT NULL,
	TENLOAI NVARCHAR(100),
	CONSTRAINT PK_LOAISP PRIMARY KEY(MALOAI)
)

CREATE TABLE DIM_SANPHAM
(
	MASP NCHAR(20) NOT NULL,
	TENSP NVARCHAR(200),	
	GIA MONEY,
	MOTA NVARCHAR(1000),
	CONSTRAINT PK_SANPHAM PRIMARY KEY(MASP)
	
)
CREATE TABLE DIM_KHACHHANG
(
	MAKH NCHAR(20) NOT NULL,
	TENKH NVARCHAR(50),
	GIOITINH NVARCHAR(50),
	DIACHI NVARCHAR(1000),
	TUOI INT,
	EMAIL NVARCHAR(100),
	DIENTHOAI INT,
	CONSTRAINT PK_KH PRIMARY KEY(MAKH)
	
)

CREATE TABLE DIM_NHANVIEN
(
	MANV NCHAR(20) NOT NULL,
	TENNV NVARCHAR(100),	
	DIACHI NVARCHAR(100),
	SDT INT,
	EMAIL NVARCHAR(50),
	CHUCVU NVARCHAR(50),
	LUONG MONEY,
	CONSTRAINT PK_NV PRIMARY KEY(MANV)	
)


CREATE TABLE FACT
(	
	MAKV NCHAR(20) NOT NULL,
	MACHINHANH NCHAR(20) NOT NULL,
	MANCC NCHAR(20) NOT NULL,
	MALOAI NCHAR(20) NOT NULL,	
	MASP NCHAR(20) NOT NULL,	
	MAKH NCHAR(20) NOT NULL,
	MANV NCHAR(20) NOT NULL,
	MATHOIGIAN NCHAR(20) NOT NULL,
	SOLUONG INT,
	GIABAN MONEY,		
	DOANHTHU MONEY,

	CONSTRAINT FK_FACT_KHUVUC FOREIGN KEY(MAKV) REFERENCES DIM_KHUVUC(MAKV),
	CONSTRAINT FK_FACT_CHINHANH FOREIGN KEY(MACHINHANH) REFERENCES DIM_CHINHANH(MACHINHANH),
	CONSTRAINT FK_FACT_NCC FOREIGN KEY(MANCC) REFERENCES DIM_NHACUNGCAP(MANCC),
	CONSTRAINT FK_FACT_LOAISP FOREIGN KEY(MALOAI) REFERENCES DIM_LOAISANPHAM(MALOAI),
	CONSTRAINT FK_FACT_SP FOREIGN KEY(MASP) REFERENCES DIM_SANPHAM(MASP),
	CONSTRAINT FK_FACT_KH FOREIGN KEY(MAKH) REFERENCES DIM_KHACHHANG(MAKH),
	CONSTRAINT FK_FACT_NV FOREIGN KEY(MANV) REFERENCES DIM_NHANVIEN(MANV), 
	CONSTRAINT FK_FACT_THOIGIAN FOREIGN KEY(MATHOIGIAN) REFERENCES DIM_THOIGIAN(MATHOIGIAN)
)

select * from DIM_CHINHANH
select * from DIM_KHACHHANG
select * from DIM_LOAISANPHAM
select * from DIM_NHACUNGCAP
select * from DIM_NHANVIEN
select * from DIM_SANPHAM
select * from DIM_THOIGIAN
select * from DIM_KHUVUC
select * from FACT

delete from DIM_CHINHANH
delete from DIM_KHACHHANG
delete from DIM_LOAISANPHAM
delete from DIM_NHACUNGCAP
delete from DIM_NHANVIEN
delete from DIM_SANPHAM
delete from DIM_THOIGIAN
delete from DIM_KHUVUC
delete from FACT

GO
CREATE PROC XOA_KHOA_NGOAI
AS
BEGIN
	ALTER TABLE FACT
	DROP CONSTRAINT FK_FACT_KHUVUC;
	ALTER TABLE FACT
	DROP CONSTRAINT FK_FACT_CHINHANH;
	ALTER TABLE FACT
	DROP CONSTRAINT FK_FACT_NCC;
	ALTER TABLE KHUVUC
	DROP CONSTRAINT FK_FACT_LOAISP;
	ALTER TABLE KHUVUC
	DROP CONSTRAINT FK_FACT_SP;
	ALTER TABLE KHUVUC
	DROP CONSTRAINT FK_FACT_KH;
	ALTER TABLE KHUVUC
	DROP CONSTRAINT FK_FACT_NV;
	ALTER TABLE KHUVUC
	DROP CONSTRAINT FK_FACT_KHUVUC;
	ALTER TABLE KHUVUC
	DROP CONSTRAINT FK_FACT_THOIGIAN;
END;
EXEC XOA_KHOA_NGOAI;